version: '3'
services:
  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:${MYSQL_TAG}
    ports:
      - ${MYSQL_PORT}:3306
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - mysql_db:/var/lib/mysql
      - "${MYSQL_INIT_SCHEMA}:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
# Uncomment this if want to run spring boot in docker container
#  wh_server:
#    container_name: ${BACKEND_CONTAINER_NAME}
#    image: ${BACKEND_IMAGE_NAME}
#    build:
#      dockerfile: ${DOCKERFILE_LOCATION}
#      context: ${ROOT_LOCATION}
#    ports:
#      - ${TOMCAT_DEBUG_PORT}:8001
#      - ${TOMCAT_HTTP_PORT}:8081
#    environment:
#      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true
#      - JDBC_URL=jdbc:mysql://mysql:3306/
#      - JDBC_USERNAME=${MYSQL_USERNAME}
#      - JDBC_PASSWORD=${MYSQL_PASSWORD}
#      - JDBC_PRIMARY_SCHEMA=wh_server
#    depends_on:
#      - mysql
volumes:
  mysql_db:
